/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VideoIndexRouteImport } from './routes/video/index'
import { Route as VideoIdRouteImport } from './routes/video/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoIndexRoute = VideoIndexRouteImport.update({
  id: '/video/',
  path: '/video/',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoIdRoute = VideoIdRouteImport.update({
  id: '/video/$id',
  path: '/video/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/video/$id': typeof VideoIdRoute
  '/video/': typeof VideoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/video/$id': typeof VideoIdRoute
  '/video': typeof VideoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/video/$id': typeof VideoIdRoute
  '/video/': typeof VideoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/video/$id' | '/video/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/video/$id' | '/video'
  id: '__root__' | '/' | '/video/$id' | '/video/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  VideoIdRoute: typeof VideoIdRoute
  VideoIndexRoute: typeof VideoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video/': {
      id: '/video/'
      path: '/video'
      fullPath: '/video/'
      preLoaderRoute: typeof VideoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video/$id': {
      id: '/video/$id'
      path: '/video/$id'
      fullPath: '/video/$id'
      preLoaderRoute: typeof VideoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  VideoIdRoute: VideoIdRoute,
  VideoIndexRoute: VideoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
